{% set name = "pyrate-limiter" %}
{% set version = "3.7.1" %}
{% set hash_val = "b268cc0b2c9f85175dbfe49ce765659a41db24d165da45395853602e5cf85819" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  entry_points:
    - cover = scripts:cover
    - lint = scripts:lint
    - test = scripts:test
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyrate_limiter
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vutran1710/PyrateLimiter
  summary: Python rate limiter using Leaky-Bucket Algorithm Family
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/vutran1710/PyrateLimiter
  dev_url: https://github.com/vutran1710/PyrateLimiter

extra:
  recipe-maintainers:
    - jwcook
