{% set name = "pyrate-limiter" %}
{% set version = "3.8.1" %}
{% set hash_val = "f012aec33147d7898a189d766decd2fecd72b58acf9d258be557cfadad975b5a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  entry_points:
    - cover = scripts:cover
    - lint = scripts:lint
    - test = scripts:test
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyrate_limiter
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vutran1710/PyrateLimiter
  summary: Python rate limiter using Leaky-Bucket Algorithm Family
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/vutran1710/PyrateLimiter
  dev_url: https://github.com/vutran1710/PyrateLimiter

extra:
  recipe-maintainers:
    - jwcook
