{% set name = "pyrate-limiter" %}
{% set version = "3.7.0" %}
{% set hash_val = "dc1e6d2c80b559f3333cb44bd822bd558f5a47946dc50cce4263a9c1c5fd8067" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 1
  noarch: python
  entry_points:
    - cover = scripts:cover
    - lint = scripts:lint
    - test = scripts:test
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyrate_limiter
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vutran1710/PyrateLimiter
  summary: Python rate limiter using Leaky-Bucket Algorithm Family
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/vutran1710/PyrateLimiter
  dev_url: https://github.com/vutran1710/PyrateLimiter

extra:
  recipe-maintainers:
    - jwcook
